name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip setuptools
          pip install buildozer cython==0.29.21

      - name: Accept Android Licenses & install SDK tools
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;34.0.0" || true

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quiz-app-apk
          path: bin/*.apk
